openapi: 3.0.0
info:
  title: EC2 Control API
  version: 1.0.0
servers:
  - url: "https://dz0ntbghgl.execute-api.ap-northeast-1.amazonaws.com/prod"
    description: "API Gateway Production"
paths:
  /ec2:
    post:
      summary: Start or Stop an EC2 instance
      operationId: controlEc2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                instanceId:
                  type: string
                action:
                  type: string
                  enum: [start, stop]
      responses:
        "200":
          description: Successfully executed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Bad request
        "500":
          description: Server error
